- name: "A-Component"
  description: "Component implementation"
  color: "bfd4f2"
- name: "A-Design-Tokens"
  color: "bfd4f2"
- name: "A-Developer-Experience"
  color: "B3C648"
- name: "A-Documentation"
  color: "bfd4f2"
- name: "A-Icons"
  color: "bfd4f2"
- name: "A-Process"
  color: "D67373"
- name: "P-Android"
  description: "Platform Android"
  color: "7D3A0A"
- name: "P-Figma"
  description: "Platform Figma"
  color: "7D3A0A"
- name: "P-iOS"
  description: "Platform iOS"
  color: "7D3A0A"
- name: "P-Web"
  description: "Platform Web"
  color: "7D3A0A"
- name: "T-Component-Design"
  color: "98e6ae"
- name: "T-Component-Development"
  color: "98e6ae"
- name: "T-New-Component"
  description: "First implementations of components."
  color: "98e6ae"
- name: "T-Other"
  description: "Questions, user support, anything else"
  color: "98e6ae"
