name: Bug report
about: Report a bug in a component
title: ''
labels: T-Defect
assignees: ''
body:
    - type: dropdown
      id: platform
      attributes: 
        label: Platform
        description: |
          Web, iOS, Android. Add the corresponding label to the issue (i.e `P-Web` for Web)
      options:
        - "Web"
        - "iOS"
        - "Android"
      validations:
          required: true
    - type: input
      id: version
      attributes: 
        label: Package version
    - type: textarea
      id: reproduction-steps
      attributes:
          label: Description
          description: Please attach screenshots, videos or logs if you can.
      validations:
          required: true