name: Automation
on:
  pull_request: {}
  push:
    branches: [main]
permissions: {}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
      - name: Set up cache
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          cache: pnpm
          node-version-file: .node-version
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Build
        run: yarn run build-storybook

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
      - name: Set up cache
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          cache: pnpm
          node-version-file: .node-version
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Check formatting
        run: pnpm format:check
